import streamlit as st
st.set("home page")
st.title("Welcome to our app") 
st.header("Create equal opportunities for all")       
st.write("This app offers an interactive game designed to help users learn sign language, providing an engaging and inclusive experience for all")
st.subheader("Game Instructions")
st.markdown("Choose your difficulty level.Learn signs with the game.Track your progress.")
st.write("Click the 'Start' button to begin")
st.write("Press 'Next' to move to the next question")
st.write("Your result will be displayed at the end of the game")
st.swrite("your taks is guessing letters in a word")
st.write("Choose your character")
if st.button('start learning')
st.write("Get ready to start learning sign language through interactive games")
st.subheader("Key Features of the Game")
st.button("Correct! +1 point")
st.button_warning("Oops, that's not correct. Try again!")
st.button("Your current score:")
st.button("Congratulations! You've unlocked Level 2!")
st.text_input("Enter a letter:")
st.markdown("Learn through fun challenges.Get immediate feedback to improve.Monitor achievements")
st.write("For more information or support, visit our website at [www.example.com]")
 